version: "3.7"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/nginx:/etc/nginx/conf.d
      - /home/ubuntu/docker-volume/jenkins/workspace/chuanione/frontend/build:/usr/share/nginx/html
      - /var/nginx/log:/log
      - /home/ubuntu/docker-volume/ssl:/var/www/html
    container_name: nginx_chu
    depends_on:
      - spring-boot


  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: Asia/Seoul
    volumes:
      - "/home/ubuntu/db_data:/var/lib/mysql"
    ports:
      - "3303:3306"
    container_name: mysql_chu

  spring-boot:
    build:
      context: ./backend/chuanione
      dockerfile: Dockerfile
    image: boot_chu
    volumes:
      - /home/ubuntu/docker-volume/jenkins/workspace/chuanione/backend/chuanione/src/main/resources/img:/img
    ports:
      - "8080:8080"
    container_name: boot_chu
    restart: always
    environment:
    - TZ=Asia/Seoul
    depends_on:
      - db

  django:
    build:
      context: ./backend/recomm
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
    #   # - ls
    #   # - python manage.py runserver 0:8000
      # - gunicorn closet.wsgi:application --bind 0.0.0.0:8000
      - gunicorn backend.wsqi.application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
    container_name: django_chu
    restart: always
    environment:
    - TZ=Asia/Seoul
    depends_on:
      - db
